CREATE USER 'backup'@'localhost';
GRANT SELECT, SHOW VIEW, RELOAD, REPLICATION CLIENT, EVENT, PROCESS, TRIGGER ON *.* TO 'backup'@'localhost';
GRANT LOCK TABLES ON *.* TO 'backup'@'localhost';
FLUSH PRIVILEGES;
